config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :items
  resources :products
  resources :spotifys
  resources :apples
  root 'spotifys#index'
  

  get 'spotify', to: 'spotify#index'
  get 'apple', to: 'apple#index'
end

app/models/apple.rb
class Apple < ApplicationRecord
  #validates :custom_url, presence: true, uniqueness: true
  #validates :name, presence: true
  #validates :custom_url, presence: true, uniqueness: true
  #default_scope -> { order(created_at: :asc) }
  self.table_name = 'apples'
  attribute :custom_url, :string
  def external_link
    "#{custom_url}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord

end

app/models/product.rb
class Product < ApplicationRecord
  #validates :custom_url, presence: true, uniqueness: true
  #validates :name, presence: true
  #validates :custom_url, presence: true, uniqueness: true
  default_scope -> { order(created_at: :asc) }
  def external_link
    "#{custom_url}"
  end
end

app/models/spotify.rb
class Spotify < ApplicationRecord
  #validates :custom_url, presence: true, uniqueness: true
  #validates :name, presence: true
  #validates :custom_url, presence: true, uniqueness: true
  #default_scope -> { order(created_at: :asc) }
  self.table_name = 'spotifys'
  self.primary_key = 'title'
  attribute :custom_url, :string
  def external_link
    "#{custom_url}"
  end
end

app/controllers/apples_controller.rb
class ApplesController < ApplicationController
  def index
    @apples = Apple.all
    @apples = Apple.order(:title)
    #render 'index'
    #@products = Product.order(created_at: :desc).all
  end

  def edit
    @apple = Apple.find(params[:id])
  end

  def update
    @apple = Apple.find(params[:id])

    if @apple.update(apple_params)
      redirect_to apples_path
      flash.now[:alert] = "success"
    else
      render :edit
    end
  end

  def create
    @apple = Apple.new(apple_params)

    if @apple.save
      redirect_to apples_path, notice: '建立完成'
    else
      render :new
    end
  end

  def destroy
    @apple = Apple.find_by(id: params[:id])
    @apple.destroy
        redirect_to apples_path, notice: '已刪除'
  end

  def new
    @apple = Apple.new
  end

  def show
    @apple = Apple.find(params[:id])
  end

  private

  def set_product
    @apple = Apple.find(params[:id])
  end

  def apple_params
    params.require(:apple).permit(:name, :custom_url, :description, :title)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    #@products = Product.order(created_at: :desc).all
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to products_path
      flash.now[:alert] = "success"
    else
      render :edit
    end
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice: '建立完成'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find_by(id: params[:id])
    @product.destroy
        redirect_to products_path, notice: '已刪除'
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :custom_url, :description)
  end

end

app/controllers/spotifys_controller.rb
class SpotifysController < ApplicationController

  def index
    @spotifys = Spotify.all
    @spotifys = Spotify.order(:title)
    #render 'index'
    #@products = Product.order(created_at: :desc).all
  end

  def edit
    @spotify = Spotify.find(params[:id])
  end

  def update
    @spotify = Spotify.find(params[:id])

    if @spotify.update(spotify_params)
      redirect_to spotifys_path
      flash.now[:alert] = "success"
    else
      render :edit
    end
  end

  def create
    @spotify = Spotify.new(spotify_params)

    if @spotify.save
      redirect_to spotifys_path, notice: '建立完成'
    else
      render :new
    end
  end

  def destroy
    @spotify = Spotify.find(params[:id])
    @spotify.destroy
        redirect_to spotifys_path, notice: '已刪除'
  end

  def new
    @spotify = Spotify.new
  end

  def show
    @spotify = Spotify.find(params[:id])
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def spotify_params
    params.require(:spotify).permit(:name, :custom_url, :description, :title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/apples/_form.html.erb
<%= form_with(model: @apple, url: apples_path, local: true) do |form| %>

<h1 class="text-2xl mb-4">新增 Podcast</h1>

<% if @apple.errors.any? %>
      <ul>
        <% @apple.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>


<div class="container w-full">
  <div class="mb-4">
    <%= form.label :title, '編號', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.number_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :name, '節目', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-4">
    <%= form.label :custom_url, '節目連結', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :custom_url, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-6">
    <%= form.label :description, '備註', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit '新增Podcast', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <%= link_to '上一頁', apples_path , class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>
  </div>
</div>
  <div class="flex">
  </div>
<% end %>

app/views/apples/edit.html.erb
<%= form_with(model: @apple, local: true) do |form| %>

<h1 class="text-2xl mb-4">修改 Podcast</h1>

<div class="container w-full">
  <div class="mb-4">
    <%= form.label :title, '編號', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.number_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :name, '節目', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-4">
    <%= form.label :custom_url, '節目連結', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field  :custom_url, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-6">
    <%= form.label :description, '備註', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit '更新Podcast', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <%= link_to '上一頁', apples_path , class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>
  </div>
</div>
<% end %>

app/views/apples/index.html.erb
<div class="relative overflow-x-auto">
  <h1 class="text-orange-900 text-5xl">Apple Pocast列表</h1>
  <div class="flex justify-end">
            <%= link_to '到Spotify頁', spotifys_path, class: 'bg-white hover:bg-blue-700 border-2 border-gray-500 p-4 rounded' %>
  </div>
    <table class="w-full border-seprate border-spacing-2 border text-2xl text-center rtl:text-right text-yellow-500">
        <thead class="text-red-700 uppercase bg-yellow-100 dark:bg-black">
            <tr>
                <th scope="col" class="px-6 py-3">
                    編號            
                </th>
                <th scope="col" class="px-6 py-3">
                    節目
                </th>
                <th scope="col" class="px-6 py-3">
                    備註
                </th>
                <th>
                    <%= button_to '新增', new_apple_path, method: :get, class: "w-full p-6 bg-blue-200 hover:bg-white" %>
                </th>
                
            </tr>
        </thead>
        <tbody>
        <% if @apples.present? %>  
          <% @apples.each_with_index do |apple, index| %>
            <tr class="border-b text-left">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= apple.title %>
                </th>
                <td class="px-6 py-4 border text-blue-500">
                    <%= link_to apple.name, apple.external_link, target: '_blank' %>
                </td>
                <td class="px-6 py-4 text-blue-700">
                    <%= apple.description %>
                </td>
                <td class="flex items-center mt-2 p-4">
                    <%= link_to '修改', edit_apple_path(apple), class: 'bg-black p-2 mr-2' %>
                    <%= button_to '刪除', apple_path(apple), method: "delete", class: 'bg-black p-2', onclick: "return confirm('確定要刪除嗎?');" %>
                </td>
                <% end %>
            </tr>
        <% else %>
            <p>No podacst</p>
          <% end %>  
        </tbody>
    </table>
</div>

app/views/apples/new.html.erb
<%= render 'form' %>

app/views/apples/show.html.erb
<h1><%= @apple.name %></h1>
<p><%= @apple.description %></p>

app/views/items/index.html.erb
<h1>Item List</h1>

<ul>
  <% @items.each do |item| %>
    <li>
      <%= item.name %> <%= link_to "View Details", item_path(item) %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podcastspotify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
      <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
      <% end %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: @product, url: products_path, local: true) do |form| %>

<% if @product.errors.any? %>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>


<div class="container w-full">
  <div class="mb-4">
    <%= form.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-4">
    <%= form.label :custom_url, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :custom_url, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-6">
    <%= form.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit '新增Podcast', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <%= link_to '上一頁', products_path , class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>
  </div>
</div>
  <div class="flex">
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>修改 Podcast</h1>

<%= form_with(model: @product, local: true) do |form| %>


<div class="container w-full">
  <div class="mb-4">
    <%= form.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-4">
    <%= form.label :custom_url, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :custom_url, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-6">
    <%= form.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit '更新Podcast', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <%= link_to '上一頁', products_path , class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>
  </div>
</div>
<% end %>

app/views/products/index.html.erb
<div class="relative overflow-x-auto">
  <h1 class="text-orange-900 text-5xl">Pocast列表</h1>
    <table class="w-full border-seprate border-spacing-2 border text-2xl text-center rtl:text-right text-yellow-500">
        <thead class="text-red-700 uppercase bg-yellow-100 dark:bg-black">
            <tr>
                <th scope="col" class="px-6 py-3">
                    
                </th>
                <th scope="col" class="px-6 py-3">
                    節目
                </th>
                <th scope="col" class="px-6 py-3">
                    備註
                </th>
                <th>
                    <%= button_to '新增', new_product_path, method: :get, class: "w-full p-6 bg-blue-200 hover:bg-white" %>
                </th>
                
            </tr>
        </thead>
        <tbody>
        <% if @products.present? %>  
          <% @products.each_with_index do |product, index| %>
            <tr class="border-b">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= index + 1 %>
                </th>
                <td class="px-6 py-4 border text-blue-500">
                    <%= link_to product.name, product.external_link, target: '_blank' %>
                </td>
                <td class="px-6 py-4 text-blue-700">
                    <%= product.description %>
                </td>
                <td class="flex items-center mt-2 p-4">
                    <%= link_to '修改', edit_product_path(product), class: '' %>
                    <%= button_to '刪除', product_path(product), method: "delete", data: { confirm: '確定要刪除嗎?' } %>
                </td>
                <% end %>
            </tr>
        <% else %>
            <p>No podacst</p>
          <% end %>  
        </tbody>
    </table>
</div>

app/views/products/new.html.erb
<h1>新增 Podcast</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p><%= @product.description %></p>

app/views/spotifys/_form.html.erb
<%= form_with(model: @spotify, url: spotifys_path, local: true) do |form| %>

<h1 class="text-2xl mb-4">新增 Podcast</h1>
<% if @spotify.errors.any? %>
      <ul>
        <% @spotify.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>


<div class="container w-full">
  <div class="mb-4">
    <%= form.label :title, '編號', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.number_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :name, '節目', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-4">
    <%= form.label :custom_url, '節目連結', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :custom_url, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-6">
    <%= form.label :description, '備註', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit '新增Podcast', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <%= link_to '上一頁', spotifys_path , class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>
  </div>
</div>
  <div class="flex">
  </div>
<% end %>

app/views/spotifys/edit.html.erb
<%= form_with(model: @spotify, local: true) do |form| %>

<h1 class="text-2xl mb-4">修改 Podcast</h1>

<div class="container w-full">
  <div class="mb-4">
    <%= form.label :title, '編號', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.number_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :name, '節目', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-4">
    <%= form.label :custom_url, '節目連結', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :custom_url, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <div class="mb-6">
    <%= form.label :description, '備註', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit '更新Podcast', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <%= link_to '上一頁', spotifys_path , class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>
  </div>
</div>
<% end %>

app/views/spotifys/index.html.erb
<div class="relative overflow-x-auto">
  <h1 class="text-orange-900 text-5xl">Spotify Pocast列表</h1>
    <table class="w-full border-seprate border-spacing-2 border text-2xl text-center rtl:text-right text-yellow-500">
        <div class="flex justify-end">
            <%= link_to '到Apple頁', apples_path, class: 'bg-white hover:bg-blue-700 border-2 border-gray-500 p-4 rounded' %>
        </div>
        <thead class="text-red-700 uppercase bg-yellow-100 dark:bg-black">
            <tr>
                <th scope="col" class="px-6 py-3">
         編號           
                </th>
                <th scope="col" class="px-6 py-3">
                    節目
                </th>
                <th scope="col" class="px-6 py-3">
                    備註
                </th>
                <th>
                    <%= button_to '新增', new_spotify_path, method: :get, class: "w-full p-6 bg-blue-200 hover:bg-white" %>
                </th>
                
            </tr>
        </thead>
        <tbody>
        <% if @spotifys.present? %>  
          <% @spotifys.each_with_index do |spotify, index| %>
            <tr class="border-b text-left">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= spotify.title %>
                </th>
                <td class="px-6 py-4 border text-blue-500">
                    <%= link_to spotify.name, spotify.external_link, target: '_blank' %>
                </td>
                <td class="px-6 py-4 text-blue-700">
                    <%= spotify.description %>
                </td>
                <td class="flex items-center mt-2 p-4">
                    <%= link_to '修改', edit_spotify_path(spotify), class: 'bg-black p-2 mr-2' %>
                    <%= button_to '刪除', spotify_path(spotify), method: "delete", class: 'p-2 bg-black', onclick: "return confirm('確定要刪除嗎?');" %>
                </td>
                <% end %>
            </tr>
        <% else %>
            <p>No podacst</p>
          <% end %>  
        </tbody>
    </table>
</div>

app/views/spotifys/new.html.erb
<%= render 'form' %>

app/views/spotifys/show.html.erb
<h1><%= @spotify.name %></h1>
<p><%= @spotify.description %></p>